// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: exported/SubBT.groovy
// ---------------------------------------------------------------------

import com.t13max.ai.behavior4j.BTNode
import org.behavior4j.test.agent.TestAgent

class SubBTDfn {
	Map<Integer, BTNode<TestAgent>> data = new HashMap<>();

	{
		
	}

	BTNode<TestAgent> getNode(int id) {
		return data.get(id)
	}

}
