#game

#实例id
instanceId: game-101
#是否阻塞主线程
park: false

#业务线程池配置
action:
  core: 1
  max: 1
  name: gameActionExecutor

#测试
test: true

#数据库
dbFile: /Users/antingbi/mc/SqlLiteDb/battle.db

netty:
  port: 23000